{% set name = "treq" %}
{% set version = "21.5.0" %}
{% set sha256 = "02ea86383fc4b57539c45a965eaa1e9fd28302cdf382d21da8430050c97be9b8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=2.7
    - pip
    - setuptools
    - incremental
  run:
    - python >=2.7
    - setuptools
    - requests >=2.1.0
    - twisted >=18.7.0
    - hyperlink >=21.0.0
    - incremental
    - six >=1.13.0
    - attrs

test:
  imports:
    - treq

about:
  home: https://github.com/twisted/treq
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python requests like API built on top of Twisted's HTTP client
  doc_url: http://treq.readthedocs.io/
  dev_url: https://github.com/twisted/treq

extra:
  recipe-maintainers:
    - synapticarbors
