# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "A7vP1IqYtegT9keE5pzc8srRzNfOVYQvtE0qrk/FVjVs5WyOcFuo7n3WMmO7/10ZtPTo8JkJhFnbajG7qDGctA7sW8JytmZb8ppiZP8u7e2cmTk+xPi007W3tuYfebcLTZTAzOpH4XFeq13zf5/fWDw/9kjYa+lMwUlmQ/cMuwaoAcWJa2LKnqbprbj9RFpqsPTg0Nag4gjdxzqCFuOa6UhRZju4fGd8J1iXZnNyGlGRWLiIWNaa0QQY3XIUsVSXEx4sCJ+LmsnJugM/df6x3s1hdKSe/3K/CMYFxlmN+v3QUuEldmaltSGovZdoLjoJOVTrjyTRHIrjNGucMM0wYl7/RNeeZKbpZY1B/faBC5yW7+ADdCRzwJ0pNuYZUSWV8CMgQOWDmZo7bb+S2wGLrJEVcaw45lb7sV6+VRjj9Ylf9bT/B2cxbaOhC3L1GAEvChW8pgsTqdosFAm5xAIT+Y6xOHriHS3m8a8Q9b86J010zxCRq+fPkHi9WbpG0bC75kuxNac8RcwOYYgaQ8bCBWKHb6SfFo5iF1av3WaNcCdIBXGc2tGkYQ9X3WMkHJr0jz8eo0jy7FbibaYtprMUe/tQqrBsUgzmtmbh+wINA2kfFdlty3iVHQsVjXaRRooSYcTEJ1mr1+DCVOV4N23FM1WENtX+wQ55fP+3yjxIp54="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
